### ISSUE TITLE
CloudFlare网站IP未更改

### ISSUE THREAD

**Issue by davidwkj** [geek5nan/koolshare-cfddns#4]
梅林版本X7.9.1，插件版本为1.1.1，经过测试发现路由器插件获取到了IP的更改，但是CloudFlare网站上并没有更新到这个IP。

**Comment by geek5nan** [comment]
> 梅林版本X7.9.1，插件版本为1.1.1，经过测试发现路由器插件获取到了IP的更改，但是CloudFlare网站上并没有更新到这个IP。

会不会是网络问题，你可以使用下边这个 curl 命令来测试一下。

```
curl -X PUT "https://api.cloudflare.com/client/v4/zones/$cfddns_zone_id/dns_records/$cfddns_record_id" \
    -H "Content-Type:application/json" \
    -H "X-Auth-Key:$cfddns_key" \
    -H "X-Auth-Email:$cfddns_email" \
     --data "{\"type\":\"A\",\"name\":\"$cfddns_name\",\"content\":\"$ip\",\"ttl\":$cfddns_ttl}"
```

将  `$cfddns_key` 、`cfddns_email`、`$cfddns_name` 、`$ip` 分别替换为你的相关信息。

**Comment by davidwkj** [comment]
执行上述命令之后，返回如下错误信息
{"success":false,"errors":[{"code":1020,"message":"Invalid DNS record identifier"}],"messages":[],"result":null}
是不是我的 参数写的不正确？

**Comment by geek5nan** [comment]
> ```
> {
>   "errors": [
>     {
>       "code": 1020,
>       "message": "Invalid DNS record identifier"
>     }
>   ],
>   "messages": [],
>   "result": null,
>   "success": false
> }
> ```

> **Invalid DNS record identifier** 
DNS 记录 ID 填错了，用正确的 ID 再试试吧。

**Comment by davidwkj** [comment]
原来获取DNS记录ID这么麻烦！之前确实是ID填错了。谢谢！
使用说明可以再丰富一下，可以让很多人少走弯路☺

**Comment by geek5nan** [comment]
嗯啊，我最近项目在忙，等有时间增加一下这些参数的获取方式说明，如果你有时间来补充的话，就更好不过了，欢迎 PR。:smiley:

**Comment by geek5nan** [comment]
关于参数获取的方式，可以用操作步骤说明文档的方式或者 shell 脚本自动获取的方式来说明。
当然，如你有更好的想法也可以自行发挥一下 : )
